name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8.0.312
        uses: actions/setup-java@v2
        with:
          java-version: '8.0.312+7'
          distribution: 'adopt'
      - name: NBM
        run: mvn clean install
